<?php if ($block->isLoggedIn()): ?>
    <li>
        <a href="/customer/account/edit/">Edit Profile</a>
    </li>
    <li>
        <a href="/sales/order/history/">Past Order</a>
    </li>
    <li>
        <a href="/customer/account/edit#changespassword">Change Password</a>
    </li>
    <li>
        <a href="/customerservicerequest/customer/customerservice">Customer Services</a>
    </li>
<?php endif; ?>
